gastronom/urls.py
from django.urls import path

from . import views

# views.ProductIndex.as_view() превращение класса в функцию
app_name = 'gastronom'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('contact_us', views.CommentCreate.as_view(), name='contact_us'),
    path('about', views.About.as_view(), name='about'),
    path('products', views.ProductIndex.as_view(), name='products'),
    path('contacts', views.Contacts.as_view(), name='contacts'),
    path('vacancies', views.VacanciesIndex.as_view(), name='vacancies'),
    path('show_product_info/<slug:product_slug>', views.ShowProduct.as_view(), name='show_product'),
    path('show_category/<slug:category_slug>', views.ShowCategory.as_view(), name='show_category'),
    path('show_vacancy_info/<slug:vacancy_slug>', views.ShowVacancy.as_view(), name='show_vacancy'),
    path('login', views.LoginUser.as_view(), name='login'),
    path('logout', views.LogoutUser.as_view(), name='logout'),
    path('comments', views.CommentsIndex.as_view(), name='comments'),
    path('show_comment/<int:pk>', views.ShowComment.as_view(), name='show_comment'),
    path('create_product', views.CreateProduct.as_view(), name='create_product'),
    path('show_product_info/<slug:product_slug>/delete', views.ProductDeleteView.as_view(), name='product_delete'),
    path('show_product_info/<slug:product_slug>/update', views.ProductUpdateView.as_view(), name='product_update'),
    path('create_vacancy', views.CreateVacancy.as_view(), name='create_vacancy'),
    path('show_vacancy_info/<slug:vacancy_slug>/delete', views.VacancyDeleteView.as_view(), name='vacancy_delete'),
    path('show_vacancy_info/<slug:vacancy_slug>/update', views.VacancyUpdateView.as_view(), name='vacancy_update'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Маршрутизатор

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gastronom.urls'))  # нужно смотреть адреса в этом приложении

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gastronom/models.py
# Create your models here.
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from unidecode import unidecode


class Category(models.Model):
    objects = models.Manager()
    name = models.CharField('Имя', max_length=20, unique=True, db_index=True)
    slug = models.SlugField('URL товара', max_length=20, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    # Описаны поля модели С ТИПАМИ ДААННЫХ
    objects = models.Manager()
    name = models.CharField('Название', max_length=50, null=False)
    # внешние ключи, нельзя удалить пока есть товары в категории
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    description = models.TextField('Описание товара', max_length=10000, null=False)
    price = models.FloatField('Цена товара')
    image = models.ImageField('Изображение', upload_to='gastronom')
    #  slug это уникальная строка идентификатор, понятная человеку. добавление индекс на слаг
    slug = models.SlugField('URL товара', max_length=50, unique=True, db_index=True)

    class Meta:
        # подробное имя для класса в единственной и множественной форме
        verbose_name = 'Товар'
        verbose_name_plural = "Товары"

    # создание автоматического слага в форме+с учетом порядкого номера для разных товаров с одинаковым названием
    def save(self, *args, **kwargs):
        last_obj = Product.objects.all().order_by('id').last()
        if last_obj:
            last_pk = last_obj.pk + 1
        else:
            last_pk = 1
        string = unidecode(str(self.name) + '_' + str(last_pk))
        # слагификация
        self.slug = slugify(string)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        # просмотр на сайте опредленного объекта из редактирования
        return reverse('gastronom:show_product', kwargs={'product_slug': self.slug})

    # замена названия объектов на названия товаров(строковое представления объекта)
    def __str__(self):
        return self.name


class VacancyConditions(models.Model):
    objects = models.Manager()
    name = models.TextField('Условие', db_index=True)

    class Meta:
        verbose_name = 'Условие'
        verbose_name_plural = "Условия"

    def __str__(self):
        return self.name


class VacancyRequirements(models.Model):
    objects = models.Manager()
    name = models.TextField('Требование', db_index=True)

    class Meta:
        verbose_name = 'Требование'
        verbose_name_plural = "Требования"

    def __str__(self):
        return self.name


class Vacancies(models.Model):
    objects = models.Manager()
    name = models.CharField('Название', max_length=40, db_index=True)
    description = models.TextField('Описание', db_index=True)
    conditions = models.ManyToManyField(VacancyConditions, verbose_name='Условия')
    requirements = models.ManyToManyField(VacancyRequirements, verbose_name='Требования')
    slug = models.SlugField('URL вакансии', max_length=50, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = "Вакансии"

    def get_absolute_url(self):
        return reverse('gastronom:show_vacancy', kwargs={'vacancy_slug': self.slug})

    def save(self, *args, **kwargs):
        last_obj = Vacancies.objects.all().order_by('id').last()
        if last_obj:
            last_pk = last_obj.pk + 1
        else:
            last_pk = 1
        string = unidecode(str(self.name) + '_' + str(last_pk))
        # слагификация
        self.slug = slugify(string)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Comments(models.Model):
    objects = models.Manager()
    first_name = models.CharField('Имя', max_length=200)
    last_name = models.CharField('Фамилия', max_length=200)
    email = models.EmailField('Email', max_length=200)
    message = models.TextField('Сообщение', max_length=1000)
    created_date = models.DateTimeField('Время публикации', auto_now=True)

    class Meta:
        verbose_name = 'Сообщение обратной связи'
        verbose_name_plural = "Сообщения обратной связи"
        ordering = ('-created_date',)

    def __str__(self):
        return self.email

gastronom/views.py
import logging
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse, reverse_lazy
# подготовленные обобщенные вьюхи
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from .models import Product, Category, Vacancies, Comments, VacancyConditions, VacancyRequirements
from .form import ProductForm, LoginUserForm, CommentForm, VacancyForm
from .utils import ContextMixin, UserData
from unidecode import unidecode

# для каждой вьюхи свой класс
logger = logging.getLogger('main')


class Index(ContextMixin, UserData, ListView):
    model = Product
    template_name = 'gastronom/index.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        logger.info('Getting index page', extra=self.get_user_data())
        context = super().get_context_data()
        user_context = self.get_user_context(title='Магазин ПАРОВОЗЪ-НН')
        context.update(user_context)
        return context


class About(ContextMixin, UserData, ListView):
    model = Product
    template_name = 'gastronom/about.html'

    def get_context_data(self, **kwargs):
        logger.info('Getting about page', extra=self.get_user_data())
        context = super().get_context_data()
        user_context = self.get_user_context(title='О компании')
        context.update(user_context)
        return context


class Contacts(ContextMixin, UserData, ListView):
    model = Product
    template_name = 'gastronom/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        logger.info('Getting contacts page', extra=self.get_user_data())
        user_context = self.get_user_context(title='Контакты')
        context.update(user_context)
        return context


class ProductIndex(ContextMixin, UserData, ListView):
    # c моделью с какой работает
    model = Product
    # с каким шаблоном
    template_name = 'gastronom/products.html'
    # название словаря, где будут все поля из модели
    context_object_name = 'products'
    # сколько объектов на странице
    paginate_by = 3
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user_context = self.get_user_context(title='Доступные товары')
        context.update(user_context)
        return context

    def get_queryset(self):
        # Сделать жадный запрос чтобы запоминалось и ускорилось полученик категорий
        queryset = ProductIndex.model.objects.all().order_by('name', 'price').select_related('category')
        logger.info('Getting products from df', extra=self.get_user_data())
        # Check the search keyword
        keyword = self.request.GET.get('src')
        if keyword is not None:
            # Set the query set based on search keyword
            queryset = Product.objects.filter(name__icontains=keyword.capitalize()).order_by(
                    'name').select_related('category')
        return queryset

    def get(self, request, *args, **kwargs):
        keyword = self.request.GET.get('src')
        if keyword is not None:
            logger.info(f'Searching product {unidecode(keyword)} from df', extra=self.get_user_data())
        return super().get(self, request, *args, **kwargs)


# механизм проверки авторизован пользователь или нет
class CreateProduct(ContextMixin, UserData, LoginRequiredMixin, CreateView):
    raise_exception = True
    # работает с формой
    form_class = ProductForm
    # с каким шаблоном работает
    template_name = 'gastronom/create.html'

    def get_success_url(self):
        # перенаправление на главную страницу
        return reverse('gastronom:products')

    def get_context_data(self, **kwargs):
        # у родителя выполнить, чтобы заполнить контекст
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Добавление товара', button='Добавить товар')
        context.update(user_context)
        return context

    def post(self, request, *args, **kwargs):
        logger.info(f'Creating product {self.request.POST}', extra=self.get_user_data())
        return super().post(self, request, *args, **kwargs)


class ShowProduct(ContextMixin, UserData, DetailView):
    model = Product
    template_name = 'gastronom/show_product.html'
    # переменная на которую нужно смотреть
    slug_url_kwarg = 'product_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        product = context['product']
        logger.info(f'Getting product page - {unidecode(product.name)}', extra=self.get_user_data())
        user_context = self.get_user_context(title=f"Детальная информация о {product}")
        context.update(user_context)
        return context


class ShowCategory(ContextMixin, UserData, ListView):
    model = Product
    template_name = 'gastronom/products.html'
    context_object_name = 'products'
    paginate_by = 3
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = Category.objects.get(slug=self.kwargs['category_slug'])
        user_context = self.get_user_context(title=f"Категория: {cat.name}", slug=cat.slug, cat=cat.name)
        context.update(user_context)
        return context

    def get_queryset(self):
        cat = self.kwargs['category_slug']
        logger.info(f'Getting products from special category - {cat}', extra=self.get_user_data())
        queryset = ShowCategory.model.objects.filter(category__slug=cat).order_by(
            'name')
        return queryset


class VacanciesIndex(ContextMixin, UserData, ListView):
    model = Vacancies
    template_name = 'gastronom/vacancies.html'
    context_object_name = 'vacancies'
    paginate_by = 3
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        logger.info(f'Getting vacancies page ', extra=self.get_user_data())
        user_context = self.get_user_context(title='Вакансии')
        context.update(user_context)
        return context


class ShowVacancy(ContextMixin, UserData, DetailView):
    model = Vacancies
    template_name = 'gastronom/show_vacancy.html'
    # переменная на которую нужно смотреть
    slug_url_kwarg = 'vacancy_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        vac = context['vacancies']
        logger.info(f'Getting vacancies page - {unidecode(vac.name)} ', extra=self.get_user_data())
        conditions = VacancyConditions.objects.filter(vacancies__id=vac.id)
        requirements = VacancyRequirements.objects.filter(vacancies__id=vac.id)
        user_context = self.get_user_context(title=f"Детальная информация о вакансии - {vac}",
                                             conditions=conditions, requirements=requirements)
        context.update(user_context)
        return context


class CommentCreate(ContextMixin, UserData, CreateView):
    # работает с формой
    form_class = CommentForm
    # с каким шаблоном работает
    template_name = 'gastronom/create.html'

    def get_success_url(self):
        # перенаправление на главную страницу
        return reverse('gastronom:index')

    def get_context_data(self, **kwargs):
        # у родителя выполнить, чтобы заполнить контекст
        context = super().get_context_data(**kwargs)
        logger.info(f'Getting comment page ', extra=self.get_user_data())
        user_context = self.get_user_context(title='Обратная связь', button='Отправить сообщение')
        context.update(user_context)
        return context

    def post(self, request, *args, **kwargs):
        logger.info(f'Creating comment {self.request.POST}', extra=self.get_user_data())
        return super().post(self, request, *args, **kwargs)


class LoginUser(ContextMixin, UserData, LoginView):
    form_class = LoginUserForm
    template_name = 'gastronom/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logger.info('Getting login page', extra=self.get_user_data())
        user_context = self.get_user_context(title='Авторизация для владельца магазина')
        context.update(user_context)
        return context

    # выполняется только если вызывается функция
    def get_success_url(self):
        return reverse('gastronom:index')


# процедура выхода
class LogoutUser(LogoutView):
    # возвращает объект только когда обращаются к next-page и потом возвращает строку(ссылку)
    next_page = reverse_lazy('gastronom:index')


class CommentsIndex(ContextMixin, UserData, LoginRequiredMixin, ListView):
    raise_exception = True
    model = Comments
    template_name = 'gastronom/comments.html'
    context_object_name = 'comments'
    paginate_by = 3
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        logger.info('Getting comments page', extra=self.get_user_data())
        user_context = self.get_user_context(title='Обратная связь')
        context.update(user_context)
        return context


class ShowComment(ContextMixin, LoginRequiredMixin, DetailView):
    model = Comments
    template_name = 'gastronom/show_comment.html'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user_context = self.get_user_context(title=f"Детальная информация комментария")
        context.update(user_context)
        return context


class ProductDeleteView(ContextMixin, LoginRequiredMixin, UserData, DeleteView):
    model = Product
    template_name = 'gastronom/product_delete.html'
    slug_url_kwarg = 'product_slug'
    raise_exception = True

    def get_success_url(self):
        return reverse('gastronom:products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

gastronom/templates/gastronom/comments.html
{% extends 'gastronom/base.html' %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
<div class="container">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for c in comments %}
        <div class="card-group">
            <div class="card">
                <div class="card-body flex-fill p-4">
                    <div class="text-center">
                        <a style="text-decoration: none; color: black" href="{% url 'gastronom:show_comment' c.pk %}">
                            <h5 class="fw-bolder">{{c.last_name|title }} {{c.first_name|title }}</h5></a>
                        <p>{{c.message| truncatechars:50 }}</p>

                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center">
                        <a class="btn btn-outline-dark mt-auto"
                           href="{% url 'gastronom:show_comment' c.pk %}">Читать полностью</a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <h1>Ни одного комментария не найдено</h1>
        {% endfor %}
    </div>
</div>

{% if page_obj.has_other_pages %}
<nav class='mt-5' aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link bg-dark text-white" href="?page={{page_obj.previous_page_number}}">Назад</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link bg-dark text-white-50">Назад</span>
        </li>
        {% endif %}

        {% for page in paginator.page_range %}
        {% if page_obj.number == page %}
        <li class="page-item active">
            <!--                     ? - дополнительный аргумент-->
            <a class="page-link" href="?page={{page}}">{{page}}</a>
        </li>
        {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
        <!--            фильтер добавления 2 или -2-->
        <li class="page-item"><a class="page-link bg-dark text-white" href="?page={{page}}">{{page}}</a></li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link bg-dark text-white" href="?page={{page_obj.next_page_number}}">Далее</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link bg-dark text-white-50">Далее</span>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif%}
{% endblock content %}

gastronom/templates/gastronom/contacts.html
{% extends 'gastronom/base.html' %}
{% block title %}{{title}}{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-start">
        <div class="col-4 title-in-page">
            Контакты
        </div>
        <article>
            <div class="row justify-content-between">
                <div class="col-5 py-5">
                    <div class="label-text">Нижний Новгород, Архангельская, 5</div>
                    <div class="row justify-content-between">
                        <div class="col-4 py-5">
                            <p class="label-text">Почтовый ящик</p>
                            <p class="label-text">alekseiz76@yandex.ru</p>
                        </div>
                        <div class="col-4 py-5">
                            <p class="label-text">Режим работы</p>
                            <p class="label-text"> Пн-Вс: 08:00 - 21:00.</p>
                        </div>
                    </div>
                    <div class="row">
                        <p class="label-text">Телефон</p>
                        <a class='tel phone' href="tel:88312128181">8 831 221 22 20 </a>
                    </div>
                </div>
                <div class="col-5">
                    <div class="embed-responsive">
                        <iframe class="embed-responsive-item"
                                src="https://yandex.ru/map-widget/v1/?um=constructor%3Ae86cd8f64e2086ab0ab79a55750a4600af808f03076539a1b227b45bfbad9e1c&amp;source=constructor"
                                width="100%" height="400"></iframe>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
{% endblock content %}

gastronom/templates/gastronom/index.html
{% extends 'gastronom/base.html' %}
{% load static %}
<!-- расширение шаблонов -->
<!-- block- тег шаблона,позволяющий вставлять HTML-код этого блока в другие шаблоны, расширяющие base.html -->
{% block title %}{{title}}{% endblock title %}

{% block content %}
<div class="imageBlock">
    <img src="{% static 'gastronom/img/parovose.jpg' %}" alt="Фото магазина">
</div>

{% endblock content %}

gastronom/templates/gastronom/products.html
{% extends 'gastronom/base.html' %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
<div class="container">
    <h1 class="title-in-page">{{cat}}</h1>
    <div class="row justify-content-between">
        <div class="col-4">
            <div class="dropdown">
                <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Все категории
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a href="{% url 'gastronom:products'%}"
                           class="dropdown-item">Вся продукция</a>
                        {% for category in categories %}
                        {% if slug == category.slug %}
                    <li><a href="{% url 'gastronom:show_category' category.slug %}"
                           class="dropdown-item disabled">{{category.name}}</a>
                    </li>
                    {% else %}
                    <li><a href="{% url 'gastronom:show_category' category.slug %}"
                           class="dropdown-item">{{category.name}}</a>
                    </li>
                    {% endif %}
                    {% empty %}
                    <h3 class="text-white">Пока нет категорий</h3>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-4">
            {% if not slug%}
            <form class="d-flex" method="get" action="">
                {% csrf_token %}
                <input class="form-control me-2" type="text" name="src" placeholder="Поиск" aria-label="Поиск">
            </form>
            {% endif %}
        </div>


        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center py-5">

            {% for product in products %}
            <div class="card-group">
                <div class="card">
                    <div class="scale"><a href="{% url 'gastronom:show_product' product.slug %}"><img
                            class="card-img-top" src="{{product.image.url}}" alt="{{product.name|title}}" width="217"
                            height="217"></a></div>
                    <!-- Product details-->
                    <div class="card-body flex-fill p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <a style="text-decoration: none; color: black"
                               href="{% url 'gastronom:show_product' product.slug %}">
                                <h5 class="fw-bolder">{{product.name|title }}</h5></a>
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <a class="link-secondary"
                           href="{% url 'gastronom:show_category' product.category.slug %}">
                            <span>{{ product.category.name }}</span> </a>
                        <!-- Product price-->
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            <span class="text-muted ">{{ product.price}} руб.</span>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center">
                            <a class="btn btn-outline-dark mt-auto"
                               href="{% url 'gastronom:show_product' product.slug %}">Читать больше</a>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <h1>Ни одного продукта не найдено</h1>
            {% endfor %}
        </div>
    </div>

    {% if page_obj.has_other_pages %}
    <nav class='mt-5' aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link bg-dark text-white" href="?page={{page_obj.previous_page_number}}">Назад</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link bg-dark text-white-50">Назад</span>
            </li>
            {% endif %}

            {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
            <li class="page-item active">
                <!-- ? - дополнительный аргумент-->
                <a class="page-link" href="?page={{page}}">{{page}}</a>
            </li>
            {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
            <!--            фильтер добавления 2 или -2-->
            <li class="page-item"><a class="page-link bg-dark text-white" href="?page={{page}}">{{page}}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link bg-dark text-white" href="?page={{page_obj.next_page_number}}">Далее</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link bg-dark text-white-50">Далее</span>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif%}
</div>
{% endblock content %}

gastronom/templates/gastronom/show_comment.html
{% extends 'gastronom/base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}

<div class="container">
    <h2 class="pro-d-title">
        {{comments.last_name}} {{comments.first_name}}
    </h2>
    <div class="m-bot15"><strong>Комментарий: </strong> <br>
        <p class="pro-price" style="word-wrap: break-word;">{{comments.message}}</p>
    </div>
    <p class="m-bot15"><b>Ответить на почту: {{comments.email}}</b></p>
    <br>
    <a href="{% url 'gastronom:comments' %}">
        <button class="btn btn-outline-dark mt-auto" type="button"><i
                class="fa fa-shopping-cart"></i> Вернуться назад
        </button>
    </a>
</div>

{% endblock content %}

gastronom/templates/gastronom/show_product.html
{% extends 'gastronom/base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}


<div class="container bootdey">
    <section class="panel">
        <div class="row">
            <div class="col-6">
                <div class="pro-img-details scale">
                    <img src="{{product.image.url}}" alt="{{product.name|title}}">
                </div>
            </div>
            <div class="col-6">
                <h2 class="pro-d-title">
                    {{product.name}}
                </h2>
                <p>{{product.description}}</p>
                <div class="product_meta">
                    <span class="posted_in"> <strong>Категория:</strong> <a
                            href="{% url 'gastronom:show_category' product.category.slug %}">
                        {{ product.category.name }}</a>.</span>
                </div>
                <div class="m-bot15"><strong>Стоимость товара: </strong> <span
                        class="pro-price">{{product.price}} руб.</span></div>
                <br>
                <p>
                    <a href="{% url 'gastronom:products' %}">
                        <button class="btn btn-outline-dark mt-auto" type="button"><i class="fa fa-shopping-cart"></i>
                            Вернуться назад
                        </button>
                    </a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'gastronom:product_update' product.slug%}">
                        <button class="btn btn-outline-danger mt-auto" type="button"><i class="fa fa-shopping-cart"></i>
                            Изменить
                        </button>
                    </a>
                    <a href="{% url 'gastronom:product_delete' product.slug%}">
                        <button class="btn btn-outline-danger mt-auto" type="button"><i class="fa fa-shopping-cart"></i>
                            Удалить
                        </button>
                    </a>
                    {% endif %}

                </p>
            </div>
        </div>
    </section>
</div>


{% endblock content %}

gastronom/templates/gastronom/show_vacancy.html
{% extends 'gastronom/base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}

<div class="container">
    <h2 class="pro-d-title">
        {{vacancies.name}}
    </h2>
    <div class="m-bot15"><strong>Описание: </strong> <br>
        <p class="pro-price" style="word-wrap: break-word;">{{vacancies.description}}</p>
    </div>
    <div class="row justify-content-center">
        <div class="col-4">
            <span class="posted_in"> <strong>Условия:</strong></span>
            {% for condition in conditions %}
            <p class="pro-price"> {{ condition.name }}</p>
            {% endfor %}
            <br>
        </div>
        <div class="col-4">
            <strong>Требования: </strong>
            {% for requirement in requirements %}
            <p class="pro-price">{{requirement.name}}</p>
            {% endfor %}
        </div>
    </div>
    <br>
    <a href="{% url 'gastronom:vacancies' %}">
        <button class="btn btn-outline-dark mt-auto" type="button"><i
                class="fa fa-shopping-cart"></i> Вернуться назад
        </button>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'gastronom:vacancy_update' vacancies.slug%}">
        <button class="btn btn-outline-danger mt-auto" type="button"><i class="fa fa-shopping-cart"></i>
            Изменить
        </button>
    </a>
    <a href="{% url 'gastronom:vacancy_delete' vacancies.slug%}">
        <button class="btn btn-outline-danger mt-auto" type="button"><i class="fa fa-shopping-cart"></i>
            Удалить
        </button>
    </a>
    {% endif %}
</div>

{% endblock content %}